/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.views;

import itson.controllers.ControlNavegacion;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.List;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;


/**
 *
 * @author jalt2
 */
public class Explorar extends javax.swing.JPanel {
    private ControlNavegacion controller;
//    private List<Usuario> perfiles;
    private int indiceActual = 0;
    private int xInicial;
    private int yInicial;
    private Timer timer;
    
    /**
     * Creates new form ExplorarPerfil
     */
    public Explorar(ControlNavegacion controller) {
        initComponents();
        this.controller = controller;
        
        xInicial = pnlCard.getX();
        yInicial = pnlCard.getY();
//        cargarPerfiles();
//        mostrarPerfil();
    }
    
    
//    private void cargarPerfiles() {
//        perfiles = new ArrayList<>();
//
//        perfiles.add(new Usuario("Sofía Ramírez", "img1.png"));
//        perfiles.add(new Usuario("Carlos Mendoza", "img2.png"));
//        perfiles.add(new Usuario("Ana López", "img3.png"));
//    }
//    
//    private void mostrarPerfil() {
//        if (indiceActual >= perfiles.size()) {
//            JOptionPane.showMessageDialog(this, "No hay más perfiles");
//            return;
//        }
//
//        Usuario u = perfiles.get(indiceActual);
//
//        lblNombre.setText(u.getNombre());
//        lblFotoPerfil.setIcon(new ImageIcon(u.getRutaImagen()));
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCard = new javax.swing.JPanel();
        lblFotoPerfil = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCarrera = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtIntereses = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtHobbies = new javax.swing.JTextArea();
        btnMeInteresa = new javax.swing.JButton();
        btnNoMeInteresa = new javax.swing.JButton();
        lblIntereses = new javax.swing.JLabel();
        lblHobbies = new javax.swing.JLabel();
        pnlMenuBotones = new javax.swing.JPanel();
        btnExplorar = new javax.swing.JButton();
        btnMatches = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();

        pnlCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFotoPerfil.setText("Foto de perfil");
        pnlCard.add(lblFotoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 180, 120));

        lblNombre.setText("Nombre");
        pnlCard.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        lblCarrera.setText("Carrera");
        pnlCard.add(lblCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        txtIntereses.setColumns(20);
        txtIntereses.setRows(5);
        jScrollPane1.setViewportView(txtIntereses);

        pnlCard.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        txtHobbies.setColumns(20);
        txtHobbies.setRows(5);
        jScrollPane2.setViewportView(txtHobbies);

        pnlCard.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, -1));

        btnMeInteresa.setBackground(new java.awt.Color(0, 153, 255));
        btnMeInteresa.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnMeInteresa.setForeground(new java.awt.Color(255, 255, 255));
        btnMeInteresa.setText("Me interesa");
        btnMeInteresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMeInteresaActionPerformed(evt);
            }
        });
        pnlCard.add(btnMeInteresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 160, -1));

        btnNoMeInteresa.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnNoMeInteresa.setForeground(new java.awt.Color(0, 0, 0));
        btnNoMeInteresa.setText("No me interesa");
        btnNoMeInteresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoMeInteresaActionPerformed(evt);
            }
        });
        pnlCard.add(btnNoMeInteresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 160, -1));

        lblIntereses.setText("Intereses");
        pnlCard.add(lblIntereses, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        lblHobbies.setText("Hobbies");
        pnlCard.add(lblHobbies, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, -1));

        btnExplorar.setText("Explorar");
        btnExplorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExplorarActionPerformed(evt);
            }
        });

        btnMatches.setText("Matches");
        btnMatches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatchesActionPerformed(evt);
            }
        });

        btnPerfil.setText("Mi Perfil");
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuBotonesLayout = new javax.swing.GroupLayout(pnlMenuBotones);
        pnlMenuBotones.setLayout(pnlMenuBotonesLayout);
        pnlMenuBotonesLayout.setHorizontalGroup(
            pnlMenuBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuBotonesLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnExplorar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnMatches, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuBotonesLayout.setVerticalGroup(
            pnlMenuBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuBotonesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlMenuBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExplorar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMenuBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMatches, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                    .addComponent(pnlMenuBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCard, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMenuBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnExplorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExplorarActionPerformed
        // TODO add your handling code here:
        controller.mostrarPanel("explorar");
    }//GEN-LAST:event_btnExplorarActionPerformed

    private void btnMatchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatchesActionPerformed
        // TODO add your handling code here:
        controller.mostrarPanel("matches");
    }//GEN-LAST:event_btnMatchesActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        // TODO add your handling code here:
        controller.mostrarPanel("miPerfil");
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnMeInteresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMeInteresaActionPerformed
        // TODO add your handling code here:
        animarDerecha();
    }//GEN-LAST:event_btnMeInteresaActionPerformed

    private void btnNoMeInteresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoMeInteresaActionPerformed
        // TODO add your handling code here:
        animarIzquierda();
    }//GEN-LAST:event_btnNoMeInteresaActionPerformed
    
    private void animarDerecha() {
        timer = new Timer(5, null);

        timer.addActionListener(e -> {
            int x = pnlCard.getX();

            pnlCard.setLocation(x + 20, pnlCard.getY());

            // Rotación fake (opcional)
            pnlCard.repaint();

            if (x > getWidth()) {
                timer.stop();
                siguientePerfil();
                resetearCard();
            }
        });

        timer.start();
    }
    
    private void animarIzquierda() {
        timer = new Timer(5, null);

        timer.addActionListener(e -> {
            int x = pnlCard.getX();

            pnlCard.setLocation(x - 20, pnlCard.getY());

            if (x < -pnlCard.getWidth()) {
                timer.stop();
                siguientePerfil();
                resetearCard();
            }
        });

        timer.start();
    }
    
    private void resetearCard() {
        pnlCard.setLocation(xInicial, yInicial);
    }
    
    private void siguientePerfil() {
        indiceActual++;
//        mostrarPerfil();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExplorar;
    private javax.swing.JButton btnMatches;
    private javax.swing.JButton btnMeInteresa;
    private javax.swing.JButton btnNoMeInteresa;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblFotoPerfil;
    private javax.swing.JLabel lblHobbies;
    private javax.swing.JLabel lblIntereses;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel pnlCard;
    private javax.swing.JPanel pnlMenuBotones;
    private javax.swing.JTextArea txtHobbies;
    private javax.swing.JTextArea txtIntereses;
    // End of variables declaration//GEN-END:variables
}
