/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.views;


import itson.controllers.ControlNavegacion;
import java.awt.BorderLayout;


/**
 *
 * @author jalt2
 */
public class Matches extends javax.swing.JPanel {
    ControlNavegacion controller;
    /**
     * Creates new form ExplorarPerfiles
     */
    public Matches(ControlNavegacion controller) {
        initComponents();
        this.controller = controller;
        
        pnlListaMatches.setLayout(new BorderLayout());

        PanelMatches lista = new PanelMatches();

        pnlListaMatches.removeAll();
        pnlListaMatches.add(lista, BorderLayout.CENTER);
        pnlListaMatches.revalidate();
        pnlListaMatches.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenidoMatches = new javax.swing.JPanel();
        btnExplorar = new javax.swing.JButton();
        btnMatches = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        pnlListaMatches = new javax.swing.JPanel();

        pnlContenidoMatches.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExplorar.setText("Explorar");
        btnExplorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExplorarActionPerformed(evt);
            }
        });
        pnlContenidoMatches.add(btnExplorar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 150, 59));

        btnMatches.setText("Matches");
        btnMatches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatchesActionPerformed(evt);
            }
        });
        pnlContenidoMatches.add(btnMatches, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 660, 160, 59));

        btnPerfil.setText("Mi Perfil");
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });
        pnlContenidoMatches.add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 660, 160, 59));

        javax.swing.GroupLayout pnlListaMatchesLayout = new javax.swing.GroupLayout(pnlListaMatches);
        pnlListaMatches.setLayout(pnlListaMatchesLayout);
        pnlListaMatchesLayout.setHorizontalGroup(
            pnlListaMatchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        pnlListaMatchesLayout.setVerticalGroup(
            pnlListaMatchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        pnlContenidoMatches.add(pnlListaMatches, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 500, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlContenidoMatches, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlContenidoMatches, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnExplorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExplorarActionPerformed
        // TODO add your handling code here:
        controller.mostrarPanel("explorar");
    }//GEN-LAST:event_btnExplorarActionPerformed

    private void btnMatchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatchesActionPerformed
        // TODO add your handling code here:
        controller.mostrarPanel("matches");
    }//GEN-LAST:event_btnMatchesActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        // TODO add your handling code here:
        controller.mostrarPanel("miPerfil");
    }//GEN-LAST:event_btnPerfilActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExplorar;
    private javax.swing.JButton btnMatches;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JPanel pnlContenidoMatches;
    private javax.swing.JPanel pnlListaMatches;
    // End of variables declaration//GEN-END:variables
}
