/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.views;


import itson.controllers.ControlNavegacion;

/**
 *
 * @author jalt2
 */
public class MiPerfil extends javax.swing.JPanel {
    private ControlNavegacion controller;
    /**
     * Creates new form MiPerfil
     */
    public MiPerfil(ControlNavegacion controller) {
        initComponents();
        this.controller = controller;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPerfil = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        lblCarrera = new javax.swing.JLabel();
        cmbCarrera = new javax.swing.JComboBox<>();
        lblSemestre = new javax.swing.JLabel();
        spnSemestre = new javax.swing.JSpinner();
        btnModificar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblFotoPerfil = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        btnExplorar = new javax.swing.JButton();
        btnMatches = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(566, 830));

        pnlPerfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mi Perfil");
        pnlPerfil.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 120, -1));

        lblNombre.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblNombre.setText("Nombre");
        pnlPerfil.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtNombre.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        pnlPerfil.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 190, -1));

        lblApellidos.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblApellidos.setText("Apellidos");
        pnlPerfil.add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        txtApellidos.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        pnlPerfil.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 190, -1));

        lblCorreo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblCorreo.setText("Correo Electronico");
        pnlPerfil.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        txtCorreo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        pnlPerfil.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 190, -1));

        lblPassword.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblPassword.setText("Contraseña");
        pnlPerfil.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        txtPassword.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        pnlPerfil.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 190, -1));

        lblCarrera.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblCarrera.setText("Carrera");
        pnlPerfil.add(lblCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        pnlPerfil.add(cmbCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 190, -1));

        lblSemestre.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblSemestre.setText("Semestre");
        pnlPerfil.add(lblSemestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, -1, -1));

        spnSemestre.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        pnlPerfil.add(spnSemestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 150, -1));

        btnModificar.setBackground(new java.awt.Color(0, 153, 255));
        btnModificar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("MODIFCAR PERFIL");
        pnlPerfil.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setText("Foto de perfil");
        pnlPerfil.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        lblFotoPerfil.setText("Foto");
        pnlPerfil.add(lblFotoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 120, 120));

        btnCerrarSesion.setText("CERRAR SESION");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        pnlPerfil.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnExplorar.setText("Explorar");
        btnExplorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExplorarActionPerformed(evt);
            }
        });
        pnlPerfil.add(btnExplorar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 150, 59));

        btnMatches.setText("Matches");
        btnMatches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatchesActionPerformed(evt);
            }
        });
        pnlPerfil.add(btnMatches, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 660, 160, 59));

        btnPerfil.setText("Mi Perfil");
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });
        pnlPerfil.add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 660, 160, 59));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnExplorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExplorarActionPerformed
        // TODO add your handling code here:
        controller.mostrarPanel("explorar");
    }//GEN-LAST:event_btnExplorarActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        // TODO add your handling code here:
        controller.mostrarPanel("miPerfil");
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnMatchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatchesActionPerformed
        // TODO add your handling code here:
        controller.mostrarPanel("matches");
    }//GEN-LAST:event_btnMatchesActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        controller.mostrarPanel("login");
    }//GEN-LAST:event_btnCerrarSesionActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnExplorar;
    private javax.swing.JButton btnMatches;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JComboBox<String> cmbCarrera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblFotoPerfil;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSemestre;
    private javax.swing.JPanel pnlPerfil;
    private javax.swing.JSpinner spnSemestre;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
